name: Publish Helm Chart

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      repositoryUrl:
        required: true
        type: string
    secrets:
      NEXUS_TOKEN:
        required: true

env:
  ALPINE_HELM_VERSION: 3.9.2
  
jobs:
  package-and-push:
    name: Helm package with dependencies
    runs-on: [self-hosted, main]
    steps:
    - uses: actions/checkout@v3
    - name: Update chart version
      env:
        TAG: ${{ inputs.tag }}
      run: sed -i "s/CHART_VERSION/$(echo $TAG | cut -c2- )/g" ./Chart.yaml
    - name: Package Helm chart
      run: docker run --rm -v $(pwd):/_ -w /_ alpine/helm:$ALPINE_HELM_VERSION package . -u
    - name: Push to Nexus
      run: |
        for file in $(ls *.tgz)
        do
          curl -u github:${{ secrets.NEXUS_TOKEN }} ${{ inputs.repositoryUrl }} --upload-file $file -v
        done
    - name: Clean up
      run: rm -fr charts/* *.tgz